docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Intro: intro.md
    - Usage: usage.md
    - Reference:
        - Configuration: configuration.md
        - Advanced: advanced.md
site_name: laminas-paginator
site_description: laminas-paginator
repo_url: 'https://github.com/laminas/laminas-paginator'
