docs_dir: docs/book
site_dir: docs/html
pages:
    - Home: index.md
    - Introduction: intro.md
    - Usage: usage.md
    - Reference:
        - Configuration: configuration.md
        - "Advanced Usage": advanced.md
site_name: zend-paginator
site_description: 'Paginate collections of data from arbitrary sources.'
repo_url: 'https://github.com/zendframework/zend-paginator'
